export const USER_ADD_IDENTIFY_ACTION= "USER_ADD_IDENTIFY";
export const USER_DROP_IDENTIFY_ACTION= "USER_DROP_IDENTIFY";

export const INICIAR_SESION_ACTION= "INICIAR_SESION";
export const CERRAR_SESION_ACTION= "CERRAR_SESION";

export const CURRICULUM_ID_ACTION ="CURRICULUM_ID_ACTION";
export const CURRICULUM_ID_REMOVE_ACTION ="CURRICULUM_ID_REMOVE_ACTION";


export const USER_PERMISSION_ACTION= "ROLE_USUARIO";
export const USER_PERMISSION_REMOVE_ACTION= "REMOVE_ROLE_USUARIO";

export const ADD_LISTA_TRABAJOS_RESULTADO_ACTION= "ADD_LISTA_TRABAJOS_RESULTADO";
export const DROP_LISTA_TRABAJOS_RESULTADO_ACTION= "DROP_LISTA_TRABAJOS_RESULTADO";
